"""Test

Revision ID: 0002_05dd2c629194
Revises: 0001_46b75c6bf9b8
Create Date: 2022-06-12 04:03:27.271868

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0002_05dd2c629194'
down_revision = '0001_46b75c6bf9b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
