"""Test

Revision ID: 0004_2e5c41629003
Revises: 0003_cd6930a45b11
Create Date: 2022-06-12 04:10:30.356205

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0004_2e5c41629003'
down_revision = '0003_cd6930a45b11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
